# docker-compose.yml
version: '3.8'

services:
  findmystore-dev:
    build: 
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    
    # ğŸš¨ .env íŒŒì¼ì„ ë¡œë“œí•˜ì—¬ Client IDë¥¼ ì£¼ì…í•©ë‹ˆë‹¤. (ë³´ì•ˆ ìœ ì§€)
    env_file:
      - .env